### ISSUE TITLE
Cloning fails due to the repository being over its data quota

### ISSUE THREAD

**Issue by dheyden** [Xanfre/T2FixResources#1]
When trying to clone the repository, a download error occurs on the T2FixResources127e.zip large file:

```
$ git clone https://github.com/Xanfre/T2FixResources.git
Cloning into 'T2FixResources'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9 (delta 1), reused 8 (delta 0), pack-reused 0
Receiving objects: 100% (9/9), done.
Resolving deltas: 100% (1/1), done.
Updating files: 100% (3/3), done.
Downloading T2FixResources127e.zip (276 MB)
Error downloading object: T2FixResources127e.zip (3c006a2): Smudge error: Error downloading T2FixResources127e.zip (3c006a2b5d253bcc869d6a72a211a9f78d344eb172f0de74ffdad889de59d53a): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

Downloading the repository as a ZIP bundle doesn't solve the problem: the T2FixResources127e.zip file obtained that way is not the actual resource file but a git-LFS metadata text file containing the following information:

```
version https://git-lfs.github.com/spec/v1
oid sha256:3c006a2b5d253bcc869d6a72a211a9f78d344eb172f0de74ffdad889de59d53a
size 275754156
```

The issue can be seen on both Windows 10 (git version 2.36.1.windows.1) and Ubuntu 20.04 LTS (WSL; git version 2.25.1).

Attachments:
- Git LFS log file (with private environment info removed)
[20220815T140935.1167113.log](https://github.com/Xanfre/T2FixResources/files/9337201/20220815T140935.1167113.log)

- T2FixResources127e.zip git LFS metadata file from direct ZIP download (either via github or using curl)
[T2FixResources127e.zip](https://github.com/Xanfre/T2FixResources/files/9337250/T2FixResources127e.zip)

**Comment by dheyden** [comment]
Hi @Xanfre , any idea how to fix this?

**Comment by Xanfre** [comment]
I am terribly sorry for the delay. I'm not sure how I have overlooked this issue for so long.

The message about the repository exceeding the quota is correct, as accounts only get 1GB of free LFS bandwidth per month. As such, tracking the files and relying on LFS to store the resources archive was probably a poor choice, especially since the files themselves are unlikely to change once published and do not benefit from tracking. I have pushed a release consisting of the archive, which should suffice since GitHub does not limit the size or delivery of binaries and, regardless of this, is a more appropriate distribution method. I have also updated the T2Fix build script to reflect this change, so pulling down these changes and attempting to build should now fetch the resources automatically.

**Comment by dheyden** [comment]
Hi Xanfre,

No problem, I've been quite busy myself this week, so I'm sorry I couldn't get back to you sooner.

Many thanks for the release! After downloading the ZIP I was able to "repair" my local copy.

Perhaps it would be worth mentioning this change in the README.md?

BR,
Didier

**Comment by Xanfre** [comment]
I'm glad you were able to get everything working. Mentioning this in the readme would probably be best to avoid confusion, so I have gone ahead and done that. I have also removed the resource archive from the tree, so cloning should no longer fail.

Thanks for mentioning this and, again, I apologize for the delay in my initial response.
